//src/app/model/row-status.model.ts
export enum RowStatus {
  REVIEW_FINANCE = 'REVIEW_FINANCE',
  APPROVED = 'APPROVED',
  REJECTED_FINANCE = 'REJECTED_FINANCE',
  REVIEW_ADMIN = 'REVIEW_ADMIN',
  REJECTED_ADMIN = 'REJECTED_ADMIN',
}
